"""Add new game settings fields

Revision ID: 5fda62f18e47
Revises: 
Create Date: 2025-03-17 01:28:52.945381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5fda62f18e47'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ship_cost', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('research_facility_cost', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_settings', schema=None) as batch_op:
        batch_op.drop_column('research_facility_cost')
        batch_op.drop_column('ship_cost')

    # ### end Alembic commands ###
