"""Add orbital settings

Revision ID: d0a795b45586
Revises: 5fda62f18e47
Create Date: 2025-03-17 02:26:11.909455

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0a795b45586'
down_revision = '5fda62f18e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('orbit_speed_factor', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_settings', schema=None) as batch_op:
        batch_op.drop_column('orbit_speed_factor')

    # ### end Alembic commands ###
