"""Add orbital settings

Revision ID: f6bcbe835f61
Revises: d0a795b45586
Create Date: 2025-03-17 03:12:02.855668

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6bcbe835f61'
down_revision = 'd0a795b45586'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_settings', schema=None) as batch_op:
        batch_op.add_column(sa.Column('mining_interval', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_settings', schema=None) as batch_op:
        batch_op.drop_column('mining_interval')

    # ### end Alembic commands ###
